print("Welcome to the Rap Name generator yo!")
hobby = input("What did you want to be when you were younger?\n")
nickname = input("What was your childhood nickname?\n")
print(" ")
print("Your rap name is....\n")
print(nickname + " Da " + hobby)